export const START_LOADING = "STATUS/START_LOADING";
export const SHOW_SUCCESS = "STATUS/SHOW_SUCCESS";
export const SHOW_ERROR = "STATUS/SHOW_ERROR";
export const GET_ALL_POSTS = "POSTS/GET_ALL_POSTS";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER = "LOGOUT_USER";
export const GET_PROFILEEDITINGFLAG="GET_PROFILEEDITINGFLAG";
export const SET_TRUE_PROFILEEDITINGFLAG="SET_TRUE_PROFILEEDITINGFLAG";
export const SET_FALSE_PROFILEEDITINGFLAG="SET_FALSE_PROFILEEDITINGFLAG";
export const RECENTLY_POSTS="RECENTLY_POSTS";
export const INTERESTED_CATERGORY="INTERESTED_CATERGORY";
export const ADD_INTERESTED="ADD_INTERESTED";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
